"""productInfoTable column 추가 sheeping_fee.

Revision ID: 0344bc13b856
Revises: 24475bed8664
Create Date: 2023-10-06 23:06:56.169696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0344bc13b856'
down_revision: Union[str, None] = '24475bed8664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('sheeping_fee', mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'sheeping_fee')
    # ### end Alembic commands ###
