"""productInfoTable column 이름 변경 itnl => intl

Revision ID: 24475bed8664
Revises: 036d96680116
Create Date: 2023-10-06 23:01:53.332823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24475bed8664'
down_revision: Union[str, None] = '036d96680116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('intl', sa.BOOLEAN(), nullable=True))
    op.drop_column('product_info', 'itnl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('itnl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('product_info', 'intl')
    # ### end Alembic commands ###
