"""productInfoTable price_desc_cursor & price_asc_cursor 생성

Revision ID: 2e0842708836
Revises: f4395c939a59
Create Date: 2023-10-13 17:03:04.937077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e0842708836'
down_revision: Union[str, None] = 'f4395c939a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('price_desc_cursor', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('product_info', sa.Column('price_asc_cursor', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('product_info', 'price_cursor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('price_cursor', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('product_info', 'price_asc_cursor')
    op.drop_column('product_info', 'price_desc_cursor')
    # ### end Alembic commands ###
