"""Product Table category_spec  추가

Revision ID: 4237f36a12ef
Revises: f815e58d2b5c
Create Date: 2023-10-14 12:34:31.524782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4237f36a12ef'
down_revision: Union[str, None] = 'f815e58d2b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('category_spec', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'category_spec')
    # ### end Alembic commands ###
