"""orderRowTable size 추가

Revision ID: 5ef6c131292e
Revises: eede7890ec2b
Create Date: 2023-10-08 02:37:27.344092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ef6c131292e'
down_revision: Union[str, None] = 'eede7890ec2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_row', sa.Column('size', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_row', 'size')
    # ### end Alembic commands ###
