"""productInfoTable payment column 3개 추가

Revision ID: 612fa2a3cfff
Revises: f1e5945c951a
Create Date: 2023-10-08 01:20:57.412951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '612fa2a3cfff'
down_revision: Union[str, None] = 'f1e5945c951a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_history', sa.Column('payment_status', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order_history', sa.Column('payment_info', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_history', 'payment_info')
    op.drop_column('order_history', 'payment_status')
    op.drop_column('order_history', 'payment_method')
    # ### end Alembic commands ###
