"""OrderHistory a data column 명 ordered_at으로 변경

Revision ID: 7ebb3a25db58
Revises: 4237f36a12ef
Create Date: 2023-10-15 23:04:37.808915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ebb3a25db58'
down_revision: Union[str, None] = '4237f36a12ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('ordered_at', mysql.DATETIME(), nullable=False))
    op.drop_column('order_history', 'order_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('order_date', sa.DATE(), nullable=False))
    op.drop_column('order_history', 'ordered_at')
    # ### end Alembic commands ###
