"""table default= func.now()로 변경 및 last_login_at 실험목적으로 추가

Revision ID: 879e90ca8b23
Revises: 7ebb3a25db58
Create Date: 2023-10-16 10:04:12.829835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '879e90ca8b23'
down_revision: Union[str, None] = '7ebb3a25db58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_at', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_at')
    # ### end Alembic commands ###
