"""UserTable 세부 기능 변경

Revision ID: a8ab07409ab2
Revises: 2e0842708836
Create Date: 2023-10-13 23:54:03.416579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a8ab07409ab2"
down_revision: Union[str, None] = "2e0842708836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("register_at", mysql.DATETIME(), nullable=False))
    op.add_column("user", sa.Column("sign_up_type", mysql.VARCHAR(length=20), nullable=False))
    op.alter_column("user", "email", existing_type=mysql.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.drop_column("user", "sign_up_type")
    op.drop_column("user", "register_at")
    # ### end Alembic commands ###
