"""history table에 payment_key 항목 추가

Revision ID: e542f9af62ee
Revises: 988fec7172c5
Create Date: 2023-10-30 13:28:41.260367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e542f9af62ee'
down_revision: Union[str, None] = '988fec7172c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('payment_key', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_history', 'payment_key')
    # ### end Alembic commands ###
