"""orderRowTable quantity 추가

Revision ID: eede7890ec2b
Revises: 612fa2a3cfff
Create Date: 2023-10-08 01:50:53.672817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eede7890ec2b'
down_revision: Union[str, None] = '612fa2a3cfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_row', sa.Column('quantity', mysql.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_row', 'quantity')
    # ### end Alembic commands ###
