"""productInfoTable column 이름 변경 sheeping_fee to shipping_fee

Revision ID: f1e5945c951a
Revises: 0344bc13b856
Create Date: 2023-10-06 23:24:22.576544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1e5945c951a'
down_revision: Union[str, None] = '0344bc13b856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('shipping_fee', mysql.INTEGER(), nullable=True))
    op.drop_column('product_info', 'sheeping_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('sheeping_fee', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_info', 'shipping_fee')
    # ### end Alembic commands ###
