"""productInfoTable size column 제거 및 price_cursor 생성

Revision ID: f4395c939a59
Revises: fd51a67d140a
Create Date: 2023-10-13 15:17:23.420279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f4395c939a59"
down_revision: Union[str, None] = "fd51a67d140a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_info", sa.Column("price_cursor", mysql.VARCHAR(length=100), nullable=True)
    )
    op.drop_column("product_info", "size")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_info", sa.Column("size", mysql.VARCHAR(length=255), nullable=True))
    op.drop_column("product_info", "price_cursor")
    # ### end Alembic commands ###
