"""UserTable user_id 타입 str전환 및  password nullable false 전환 

Revision ID: f815e58d2b5c
Revises: a8ab07409ab2
Create Date: 2023-10-14 01:53:04.576310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f815e58d2b5c"
down_revision: Union[str, None] = "a8ab07409ab2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop address foreign key constraint
    op.drop_constraint("user_address_ibfk_1", "user_address", type_="foreignkey")

    # # Drop history foreign key constraint
    op.drop_constraint("order_history_ibfk_1", "order_history", type_="foreignkey")

    # Alter column types
    op.alter_column(
        "order_history",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'10000'"),
        server_default=None,
    )

    op.alter_column("user", "password", existing_type=mysql.VARCHAR(length=255), nullable=True)

    op.alter_column(
        "user_address",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )

    # Recreate foreign key constraint
    op.create_foreign_key("order_history_ibfk_1", "order_history", "user", ["user_id"], ["user_id"])

    # Recreate foreign key constraint
    op.create_foreign_key("user_address_ibfk_1", "user_address", "user", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_address",
        "user_id",
        existing_type=mysql.VARCHAR(length=50),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column("user", "password", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.alter_column(
        "user",
        "user_id",
        existing_type=mysql.VARCHAR(length=50),
        type_=mysql.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("'10000'"),
    )
    op.alter_column(
        "order_history",
        "user_id",
        existing_type=mysql.VARCHAR(length=50),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
