"""Size Table 추가

Revision ID: faaa518ca4fa
Revises: 5ef6c131292e
Create Date: 2023-10-12 22:47:27.023967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'faaa518ca4fa'
down_revision: Union[str, None] = '5ef6c131292e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('size_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', mysql.INTEGER(), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('available', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['product_info.sku'], ),
    sa.PrimaryKeyConstraint('size_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size')
    # ### end Alembic commands ###
