"""Size Table updated_at 타입 DATE -> DATETIME으로 변경

Revision ID: fd51a67d140a
Revises: faaa518ca4fa
Create Date: 2023-10-12 23:01:54.763472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd51a67d140a'
down_revision: Union[str, None] = 'faaa518ca4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size', 'updated_at',
               existing_type=sa.DATE(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
