import { productCardProps } from "@/app/types/type";
export const mockDB: productCardProps[] = [
    {
        sku: 1,
        brand: "adidas originals",
        productName: "handball spezial black",
        productId: "db3021",
        price: 110000,
        shippingFee: 19000,
        intl: true,
        imgType: "avif",
    },
    {
        sku: 2,
        brand: "nike",
        productName: "jacquemus force black",
        productId: "DR0424-001",
        price: 120000,
        shippingFee: 19000,
        intl: true,
        imgType: "webp",
    },
    {
        sku: 3,
        brand: "adidas originals",
        productName: "tobacco pantone mesa",
        productId: "gy7396",
        price: 130000,
        shippingFee: 19000,
        intl: true,
        imgType: "avif",
    },
    {
        sku: 4,
        brand: "adidas originals",
        productName: "handball spezial black",
        productId: "db3021",
        price: 140000,
        shippingFee: 3000,
        intl: false,
        imgType: "avif",
    },
];
